name: My-First-GitHub-Action

on:
    push:
        branches: [ "main" ]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: |
            echo "Welcome to GitHub-Actions"
            ls
            cat README.md 