name: Sum & Product with Input numbers

on:
  workflow_dispatch:
    
    inputs:
        number-1:
            description: 'Enter first number'
            default: '0'
            required: true

        number-2:
            description: 'Enter second number'
            default: '0'
            required: true  
                
jobs:
    sum-with-input:
        runs-on: ubuntu-latest

        steps:
          - name: Add the numbers
            id: sum
            run: |
                sum=$((${{ inputs.number-1 }} + ${{ inputs.number-2 }}))
                echo "sum=$sum" >> $GITHUB_OUTPUT

          - name: Get the ouput of Sum
            run: echo "The sum of ${{ inputs.number-1 }} and ${{ inputs.number-2 }} is ${{ steps.sum.outputs.sum }}"
    
    product-with-input:
        runs-on: ubuntu-latest
        steps: 
            
          - name: Multiply the numbers
            id: product
            run: |
                product=$((${{ inputs.number-1 }} * ${{ inputs.number-2 }}))
                echo "product=$product"  >> $GITHUB_OUTPUT


          - name: Get the ouput of product
            run: echo "The product of ${{ inputs.number-1 }} and ${{ inputs.number-2 }} is ${{ steps.product.outputs.product }}"      