name: Terraform-Workflow

on:
  push:
    branches:
        - main
        
  pull_request:
    branches:
        - main

permissions:
    contents: read    
    
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: "ap-south-1"    
        
jobs:
    terraform-resource:
        runs-on: ubuntu-latest
        
        defaults:
            run:
              shell: bash

        steps:

          - name: Chekout repository
            uses: actions/checkout@v4

          - name: Setup terraform
            uses: hashicorp/setup-terraform@v3
            with:
                cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

          - name: Initialize & Run Terraform config
            run: |
                 terraform init
                 terraform plan
                 terraform apply -auto-approve      
                
                