name: Workflow filters and Activities

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - '!feature/*'

    pull_request:
        types:
            - opened
            - closed
    
        paths-ignore: 
            - README.md
        branches:
            - main        
 
jobs:
 workflow_filter:
    runs-on: ubuntu-latest
    steps:
       - name: Echo whatever provided
         run: echo this workflow is executed for event type - ${{ github.event }}

